// broker/lib/openapi-spec.js — V4 OpenAPI 3.1 集中式规范
// Generated by hand to keep all braces on separate lines (no inline one-liners with multiple braces).

import { BROKER_VERSION } from '../version.js';

function ref(name) {
  return { $ref: '#/components/schemas/' + name };
}
function respRef(name) {
  return { $ref: '#/components/responses/' + name };
}
function desc(s) { return { description: s }; }
function jsonOK(schemaName) {
  return { description: 'OK', content: { 'application/json': { schema: ref(schemaName) } } };
}
function jsonOKList(schemaName) {
  return {
    description: 'OK',
    content: { 'application/json': { schema: { type: 'object', properties: { items: { type: 'array', items: ref(schemaName) } } } } },
  };
}

const p = {
  '/health': {
    get: { tags: ['health'], summary: 'Liveness', security: [], responses: { 200: jsonOK('Health') } },
  },
  '/ready': {
    get: { tags: ['health'], summary: 'Readiness (deps probed)', security: [], responses: { 200: desc('Ready'), 503: desc('Not ready') } },
  },
  '/metrics': {
    get: { tags: ['health'], summary: 'Prometheus metrics', security: [], responses: { 200: { description: 'Text exposition' } } },
  },
  '/api/v1/login': {
    post: {
      tags: ['auth'],
      summary: 'Compatibility login; disabled in strict profile',
      requestBody: { content: { 'application/json': { schema: ref('LoginRequest') } } },
      responses: { 200: jsonOK('LoginResponse'), 401: respRef('Unauthorized') },
    },
  },
  '/api/v1/login/mfa': {
    post: {
      tags: ['auth'],
      summary: 'Submit MFA code (TOTP / WebAuthn / SMS)',
      requestBody: {
        content: { 'application/json': { schema: { type: 'object', required: ['mfa_token', 'code'], properties: { mfa_token: { type: 'string' }, code: { type: 'string' }, factor: { type: 'string', enum: ['totp', 'webauthn', 'sms', 'recovery'] } } } } },
      },
      responses: { 200: jsonOK('LoginResponse'), 401: respRef('Unauthorized') },
    },
  },
  '/api/v1/login/webauthn/begin': {
    post: {
      tags: ['auth'],
      summary: 'Begin phishing-resistant WebAuthn authentication',
      security: [],
      requestBody: { content: { 'application/json': { schema: { type: 'object', required: ['client'], properties: { client: { type: 'string' } } } } } },
      responses: { 200: desc('PublicKeyCredentialRequestOptionsJSON'), 403: respRef('Forbidden') },
    },
  },
  '/api/v1/login/webauthn/finish': {
    post: {
      tags: ['auth'],
      summary: 'Verify WebAuthn assertion and establish HttpOnly session',
      security: [],
      requestBody: { content: { 'application/json': { schema: { type: 'object', required: ['client', 'response'], properties: { client: { type: 'string' }, response: { type: 'object' } } } } } },
      responses: { 200: jsonOK('LoginResponse'), 401: respRef('Unauthorized') },
    },
  },
  '/api/v1/login/recovery': {
    post: {
      tags: ['auth'],
      summary: 'Submit recovery code',
      requestBody: { content: { 'application/json': { schema: { type: 'object', required: ['client', 'code'], properties: { client: { type: 'string' }, code: { type: 'string' } } } } } },
      responses: { 200: desc('OK'), 401: respRef('Unauthorized') },
    },
  },
  '/api/v1/logout': {
    post: { tags: ['auth'], summary: 'Logout', responses: { 200: desc('OK') } },
  },
  '/api/v1/me': {
    get: { tags: ['me'], summary: 'Current identity', responses: { 200: jsonOK('Me') } },
  },
  '/api/v1/me/change-password': {
    post: {
      tags: ['me'],
      summary: 'Change password',
      requestBody: { content: { 'application/json': { schema: { type: 'object', required: ['old_password', 'new_password'], properties: { old_password: { type: 'string', format: 'password' }, new_password: { type: 'string', format: 'password' } } } } } },
      responses: { 200: desc('OK'), 401: respRef('Unauthorized') },
    },
  },
  '/api/v1/me/totp/setup': {
    post: { tags: ['me'], summary: 'Begin TOTP setup', responses: { 200: desc('OK, returns otpauth URL and secret') } },
  },
  '/api/v1/me/totp/verify': {
    post: {
      tags: ['me'],
      summary: 'Verify TOTP and enable',
      requestBody: { content: { 'application/json': { schema: { type: 'object', required: ['code'], properties: { code: { type: 'string' } } } } } },
      responses: { 200: desc('Enabled'), 401: respRef('Unauthorized') },
    },
  },
  '/api/v1/me/totp/disable': {
    post: { tags: ['me'], summary: 'Disable TOTP', responses: { 200: desc('OK') } },
  },
  '/api/v1/me/webauthn/register/begin': {
    post: { tags: ['me'], summary: 'Begin WebAuthn registration', responses: { 200: desc('OK, returns challenge') } },
  },
  '/api/v1/me/webauthn/register/finish': {
    post: { tags: ['me'], summary: 'Finish WebAuthn registration', requestBody: { content: { 'application/json': { schema: { type: 'object' } } } }, responses: { 200: desc('OK') } },
  },
  '/api/v1/me/webauthn/credentials': {
    get: { tags: ['me'], summary: 'List WebAuthn credentials', responses: { 200: desc('OK') } },
  },
  '/api/v1/me/webauthn/credentials/{id}': {
    delete: { tags: ['me'], summary: 'Delete a WebAuthn credential', parameters: [{ in: 'path', name: 'id', required: true, schema: { type: 'string' } }], responses: { 200: desc('OK') } },
  },
  '/api/v1/me/reauth/webauthn/begin': {
    post: { tags: ['auth'], summary: 'Begin WebAuthn reauthentication for a sensitive operation', responses: { 200: desc('PublicKeyCredentialRequestOptionsJSON') } },
  },
  '/api/v1/me/reauth/webauthn/finish': {
    post: { tags: ['auth'], summary: 'Finish WebAuthn reauthentication and issue a five-minute one-use grant', responses: { 200: desc('One-use reauthentication grant'), 401: respRef('Unauthorized') } },
  },
  '/api/v1/admin/approvals': {
    post: { tags: ['admin'], summary: 'Request payload-bound approval for a sensitive operation', responses: { 201: desc('Pending approval'), 403: respRef('Forbidden') } },
  },
  '/api/v1/admin/approvals/{id}/approve': {
    post: {
      tags: ['admin'], summary: 'Approve using a distinct administrator and one-use WebAuthn grant',
      parameters: [{ in: 'path', name: 'id', required: true, schema: { type: 'string' } }],
      responses: { 200: desc('Approved'), 403: respRef('Forbidden') },
    },
  },
  '/api/v1/secrets': {
    get: { tags: ['secrets'], summary: 'List visible secrets', responses: { 200: jsonOKList('Secret') } },
  },
  '/api/v1/secrets/resolve': {
    post: {
      tags: ['secrets'],
      summary: 'Resolve a secret to plaintext (audited)',
      deprecated: true,
      requestBody: { content: { 'application/json': { schema: { type: 'object', required: ['name'], properties: { name: { type: 'string' } } } } } },
      responses: { 200: desc('OK'), 403: respRef('Forbidden'), 404: respRef('NotFound') },
    },
  },
  '/api/v1/services': {
    get: { tags: ['services'], summary: 'List visible services', responses: { 200: desc('OK') } },
  },
  '/api/v1/proxy/{service}': {
    post: {
      tags: ['proxy'],
      summary: 'Legacy free-form proxy; disabled in strict profile',
      deprecated: true,
      parameters: [{ in: 'path', name: 'service', required: true, schema: { type: 'string' } }],
      requestBody: { content: { 'application/json': { schema: ref('ProxyRequest') } } },
      responses: {
        200: { description: 'Upstream response' },
        400: respRef('BadRequest'),
        401: respRef('Unauthorized'),
        403: respRef('Forbidden'),
        404: respRef('NotFound'),
        429: respRef('RateLimited'),
        502: { description: 'Upstream error', content: { 'application/json': { schema: ref('Error') } } },
        503: { description: 'Service unavailable (e.g. secret expired)', content: { 'application/json': { schema: ref('Error') } } },
      },
    },
  },
  '/api/v2/operations/{service}/{operation}': {
    post: {
      tags: ['operations'],
      summary: 'Invoke a policy-defined typed provider operation',
      parameters: [
        { in: 'path', name: 'service', required: true, schema: { type: 'string' } },
        { in: 'path', name: 'operation', required: true, schema: { type: 'string' } },
      ],
      requestBody: { content: { 'application/json': { schema: ref('TypedOperationRequest') } } },
      responses: {
        200: { description: 'Provider business response; credentials are never returned' },
        400: respRef('BadRequest'),
        401: respRef('Unauthorized'),
        403: respRef('Forbidden'),
        404: respRef('NotFound'),
        429: respRef('RateLimited'),
        502: { description: 'Upstream error', content: { 'application/json': { schema: ref('Error') } } },
      },
    },
  },
  '/api/v1/api-keys': {
    get: { tags: ['api-keys'], summary: 'List API keys', responses: { 200: jsonOKList('ApiKey') } },
    post: {
      tags: ['api-keys'],
      summary: 'Create API key',
      requestBody: { content: { 'application/json': { schema: { type: 'object', required: ['name'], properties: { name: { type: 'string' }, scopes: { type: 'array', items: { type: 'string' } }, ttl_seconds: { type: 'integer' } } } } } },
      responses: { 200: { description: 'OK, returns key and secret' }, 401: respRef('Unauthorized') },
    },
  },
  '/api/v1/api-keys/{id}': {
    delete: { tags: ['api-keys'], summary: 'Revoke API key', parameters: [{ in: 'path', name: 'id', required: true, schema: { type: 'string' } }], responses: { 200: desc('OK') } },
  },
  '/api/v1/api-keys/master': {
    post: { tags: ['api-keys'], summary: 'Create master key (30d TTL)', responses: { 200: desc('OK') } },
  },
  '/api/v1/api-keys/issue-child': {
    post: { tags: ['api-keys'], summary: 'Issue a child key (master key only)', responses: { 200: desc('OK, 1h TTL') } },
  },
  '/api/v1/admin/secrets': {
    get: { tags: ['admin'], summary: 'List all secrets (admin)', responses: { 200: desc('OK') } },
    post: {
      tags: ['admin'],
      summary: 'Create secret',
      requestBody: { content: { 'application/json': { schema: { type: 'object', required: ['name', 'type'], properties: { name: { type: 'string' }, type: { type: 'string' }, fields: { type: 'object' } } } } } },
      responses: { 200: desc('OK') },
    },
  },
  '/api/v1/admin/services': {
    get: { tags: ['admin'], summary: 'List all services (admin)', responses: { 200: desc('OK') } },
    post: { tags: ['admin'], summary: 'Create service from template', responses: { 200: desc('OK') } },
  },
  '/api/v1/admin/services/{name}/test': {
    post: {
      tags: ['admin'],
      summary: 'Test one registered read-only service operation',
      parameters: [{ in: 'path', name: 'name', required: true, schema: { type: 'string' } }],
      requestBody: {
        required: true,
        content: { 'application/json': { schema: ref('ServiceTestRequest') } },
      },
      responses: {
        200: { description: 'Redacted provider response preview' },
        400: respRef('BadRequest'),
        401: respRef('Unauthorized'),
        403: respRef('Forbidden'),
        404: respRef('NotFound'),
        503: { description: 'Credential health evidence unavailable', content: { 'application/json': { schema: ref('Error') } } },
      },
    },
  },
  '/api/v1/admin/clients': {
    get: { tags: ['admin'], summary: 'List all clients (admin)', responses: { 200: desc('OK') } },
    post: { tags: ['admin'], summary: 'Create client', responses: { 200: desc('OK') } },
  },
  '/api/v1/admin/audit': {
    get: {
      tags: ['admin'],
      summary: 'Query audit log',
      parameters: [
        { in: 'query', name: 'since', schema: { type: 'string' } },
        { in: 'query', name: 'cn', schema: { type: 'string' } },
        { in: 'query', name: 'action', schema: { type: 'string' } },
        { in: 'query', name: 'limit', schema: { type: 'integer', default: 100 } },
      ],
      responses: { 200: desc('OK') },
    },
  },
  '/api/v1/admin/audit/stream': {
    get: { tags: ['admin'], summary: 'SSE stream of audit events', responses: { 200: { description: 'text/event-stream' } } },
  },
  '/api/v1/admin/reload': {
    post: { tags: ['admin'], summary: 'Hot-reload broker.yaml (requires 2FA for admin)', responses: { 200: desc('OK') } },
  },
  '/api/v1/healthcheck/status': {
    get: { tags: ['healthcheck'], summary: 'Last healthcheck state', responses: { 200: desc('OK') } },
  },
  '/api/v1/healthcheck/run': {
    post: { tags: ['healthcheck'], summary: 'Run healthcheck now', responses: { 200: desc('OK') } },
  },
  '/api/v1/healthcheck/stream': {
    get: { tags: ['healthcheck'], summary: 'SSE stream of healthcheck events', responses: { 200: { description: 'text/event-stream' } } },
  },
  '/api/v1/alerts/history': {
    get: { tags: ['admin'], summary: 'Alert history', responses: { 200: desc('OK') } },
  },
  '/api/v1/workload-identity/assume': {
    post: {
      tags: ['admin'],
      summary: 'OIDC to STS assume role (broker-side)',
      requestBody: { content: { 'application/json': { schema: { type: 'object', required: ['provider', 'role'], properties: { provider: { type: 'string', enum: ['aliyun', 'aws', 'gcp'] }, role: { type: 'string' }, oidc_token: { type: 'string' } } } } } },
      responses: { 200: desc('OK') },
    },
  },
};

const s = {
  Error: {
    type: 'object',
    required: ['error'],
    properties: {
      error: { type: 'string' },
      detail: { type: 'string' },
      request_id: { type: 'string' },
      retry_after_ms: { type: 'integer' },
      docs: { type: 'string' },
    },
  },
  ProxyRequest: {
    type: 'object',
    required: ['method', 'path'],
    properties: {
      method: { type: 'string', enum: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'] },
      path: { type: 'string', pattern: '^/', maxLength: 2048 },
      query: { type: 'object', additionalProperties: { type: 'string' } },
      headers: { type: 'object', additionalProperties: { type: 'string' } },
      body: {},
      timeout_ms: { type: 'integer', minimum: 1000, maximum: 60000, default: 30000 },
      stream: { type: 'boolean', default: false },
    },
  },
  TypedOperationRequest: {
    type: 'object',
    additionalProperties: false,
    properties: {
      parameters: { type: 'object', additionalProperties: true },
      body: {},
    },
  },
  ServiceTestRequest: {
    type: 'object',
    additionalProperties: false,
    required: ['operation_id'],
    properties: {
      operation_id: { type: 'string', pattern: '^[a-z0-9][a-z0-9_.-]{0,63}$' },
      parameters: { type: 'object', additionalProperties: true },
    },
  },
  LoginRequest: {
    type: 'object',
    required: ['password'],
    properties: {
      client: { type: 'string' },
      password: { type: 'string', format: 'password' },
    },
  },
  LoginResponse: {
    type: 'object',
    properties: {
      expires_at: { type: 'string', format: 'date-time' },
      cn: { type: 'string' },
      role: { type: 'string', enum: ['developer', 'admin', 'ci'] },
      mfa_required: { type: 'boolean' },
      mfa_token: { type: 'string' },
      factors_verified: { type: 'array', items: { type: 'string' } },
    },
  },
  Me: {
    type: 'object',
    properties: {
      name: { type: 'string' },
      cn: { type: 'string' },
      role: { type: 'string' },
      allow_password_login: { type: 'boolean' },
      has_password: { type: 'boolean' },
      password_set_at: { type: 'string', format: 'date-time' },
      totp_enabled: { type: 'boolean' },
      preferred_2fa: { type: 'string' },
      cert_fingerprint_sha256: { type: 'string' },
      cert_expires_at: { type: 'string', format: 'date-time' },
      risk_score: { type: 'number' },
      rate_limit: { type: 'string' },
    },
  },
  ApiKey: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      name: { type: 'string' },
      client: { type: 'string' },
      scopes: { type: 'array', items: { type: 'string' } },
      rate_limit: { type: 'string' },
      rate_limit_per_minute: { type: 'integer' },
      rate_limit_per_hour: { type: 'integer' },
      rate_limit_per_day: { type: 'integer' },
      ip_whitelist: { type: 'array', items: { type: 'string' } },
      allowed_secrets: { type: 'array', items: { type: 'string' } },
      allowed_services: { type: 'array', items: { type: 'string' } },
      allowed_operations: { type: 'array', items: { type: 'string' } },
      created_at: { type: 'string', format: 'date-time' },
      expires_at: { type: 'string', format: 'date-time' },
      revoked_at: { type: 'string', format: 'date-time' },
      is_master: { type: 'boolean' },
      fingerprint_prefix: { type: 'string' },
    },
  },
  Secret: {
    type: 'object',
    properties: {
      name: { type: 'string' },
      type: { type: 'string' },
      description: { type: 'string' },
      last_used_at: { type: 'string', format: 'date-time' },
      last_rotated_at: { type: 'string', format: 'date-time' },
      has_value: { type: 'boolean' },
    },
  },
  Service: {
    type: 'object',
    properties: {
      name: { type: 'string' },
      type: { type: 'string' },
      auth_type: { type: 'string' },
      upstream: { type: 'string' },
      category: { type: 'string' },
      allow_methods: { type: 'array', items: { type: 'string' } },
      allow_paths: { type: 'array', items: { type: 'string' } },
      healthcheck: { type: 'object' },
      environment: { type: 'string' },
      operations: { type: 'object', additionalProperties: { type: 'object' } },
    },
  },
  Health: {
    type: 'object',
    properties: {
      status: { type: 'string', enum: ['ok', 'degraded', 'down'] },
      version: { type: 'string' },
      uptime: { type: 'number' },
      checks: { type: 'object' },
    },
  },
};

const r = {
  BadRequest: { description: 'Bad request', content: { 'application/json': { schema: ref('Error') } } },
  Unauthorized: { description: 'Unauthenticated', content: { 'application/json': { schema: ref('Error') } } },
  Forbidden: { description: 'Forbidden', content: { 'application/json': { schema: ref('Error') } } },
  NotFound: { description: 'Not found', content: { 'application/json': { schema: ref('Error') } } },
  RateLimited: { description: 'Rate limited', content: { 'application/json': { schema: ref('Error') } } },
  InternalError: { description: 'Internal error', content: { 'application/json': { schema: ref('Error') } } },
};

export const OPENAPI_SPEC = {
  openapi: '3.1.0',
  info: {
    title: 'Secret Broker API',
    version: BROKER_VERSION,
    description: 'mTLS Secret Broker for AI clients. AI never sees plaintext keys.',
  },
  servers: [
    { url: 'https://broker.52trz.com:8443', description: 'Aliyun production' },
    { url: 'https://broker-bk.52trz.com:8443', description: 'Tencent production (failover)' },
    { url: 'http://localhost:8443', description: 'Local dev' },
  ],
  security: [{ mtls: [] }, { bearerAuth: [] }, { sessionCookie: [] }],
  tags: [
    { name: 'health', description: 'Health / ready / metrics' },
    { name: 'auth', description: 'Authentication' },
    { name: 'me', description: 'Self-service profile' },
    { name: 'secrets', description: 'Secret listing and resolve' },
    { name: 'services', description: 'Service listing' },
    { name: 'proxy', description: 'Proxy external API' },
    { name: 'api-keys', description: 'API Key management' },
    { name: 'admin', description: 'Admin operations' },
    { name: 'healthcheck', description: 'Credential self-check' },
  ],
  paths: p,
  components: {
    securitySchemes: {
      mtls: { type: 'mutualTLS', description: 'mTLS client certificate' },
      bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'API Key (mb_live_xxx)' },
      sessionCookie: { type: 'apiKey', in: 'cookie', name: 'broker_session' },
    },
    schemas: s,
    responses: r,
  },
};

export default OPENAPI_SPEC;
