// broker/lib/openapi-spec.js — V4 OpenAPI 3.1 集中式规范
// Generated by hand to keep all braces on separate lines (no inline one-liners with multiple braces).

import { BROKER_VERSION } from '../version.js';

function ref(name) {
  return { $ref: '#/components/schemas/' + name };
}
function respRef(name) {
  return { $ref: '#/components/responses/' + name };
}
function desc(s) { return { description: s }; }
function jsonOK(schemaName) {
  return { description: 'OK', content: { 'application/json': { schema: ref(schemaName) } } };
}
function jsonOKList(schemaName) {
  return {
    description: 'OK',
    content: { 'application/json': { schema: { type: 'object', properties: { items: { type: 'array', items: ref(schemaName) } } } } },
  };
}

const p = {
  '/health': {
    get: { tags: ['health'], summary: 'Public liveness (fingerprint-free)', security: [], responses: { 200: desc('{ status: ok }') } },
  },
  '/api/v1/health': {
    get: { tags: ['health'], summary: 'Authenticated ops health', responses: { 200: jsonOK('Health'), 401: respRef('Unauthorized') } },
  },
  '/ready': {
    get: { tags: ['health'], summary: 'Readiness (local health socket only)', security: [], responses: { 200: desc('Ready'), 503: desc('Not ready') } },
  },
  '/metrics': {
    get: { tags: ['health'], summary: 'Prometheus metrics (local scrape or admin)', responses: { 200: { description: 'Text exposition' }, 401: respRef('Unauthorized') } },
  },
  '/api/v1/login': {
    post: {
      tags: ['auth'],
      summary: 'Password login (may require MFA)',
      requestBody: { content: { 'application/json': { schema: ref('LoginRequest') } } },
      responses: { 200: jsonOK('LoginResponse'), 401: respRef('Unauthorized') },
    },
  },
  '/api/v1/login/mfa': {
    post: {
      tags: ['auth'],
      summary: 'Submit legacy MFA code (TOTP or recovery code)',
      requestBody: {
        content: { 'application/json': { schema: { type: 'object', required: ['mfa_token', 'code'], properties: { mfa_token: { type: 'string' }, code: { type: 'string' }, factor: { type: 'string', enum: ['totp', 'recovery'] } } } } },
      },
      responses: { 200: jsonOK('LoginResponse'), 401: respRef('Unauthorized') },
    },
  },
  '/api/v1/login/recovery': {
    post: {
      tags: ['auth'],
      summary: 'Submit recovery code',
      requestBody: { content: { 'application/json': { schema: { type: 'object', required: ['client', 'code'], properties: { client: { type: 'string' }, code: { type: 'string' } } } } } },
      responses: { 200: desc('OK'), 401: respRef('Unauthorized') },
    },
  },
  '/api/v1/logout': {
    post: { tags: ['auth'], summary: 'Logout', responses: { 200: desc('OK') } },
  },
  '/api/v1/me': {
    get: { tags: ['me'], summary: 'Current identity', responses: { 200: jsonOK('Me') } },
  },
  '/api/v1/me/change-password': {
    post: {
      tags: ['me'],
      summary: 'Change password',
      requestBody: { content: { 'application/json': { schema: { type: 'object', required: ['old_password', 'new_password'], properties: { old_password: { type: 'string', format: 'password' }, new_password: { type: 'string', format: 'password' } } } } } },
      responses: { 200: desc('OK'), 401: respRef('Unauthorized') },
    },
  },
  '/api/v1/me/totp/setup': {
    post: { tags: ['me'], summary: 'Begin TOTP setup', responses: { 200: desc('OK, returns otpauth URL and secret') } },
  },
  '/api/v1/me/totp/verify': {
    post: {
      tags: ['me'],
      summary: 'Verify TOTP and enable',
      requestBody: { content: { 'application/json': { schema: { type: 'object', required: ['code'], properties: { code: { type: 'string' } } } } } },
      responses: { 200: desc('Enabled'), 401: respRef('Unauthorized') },
    },
  },
  '/api/v1/me/totp/disable': {
    post: { tags: ['me'], summary: 'Disable TOTP', responses: { 200: desc('OK') } },
  },
  '/api/v1/secrets': {
    get: { tags: ['secrets'], summary: 'List visible secrets', responses: { 200: jsonOKList('Secret') } },
  },
  '/api/v1/secrets/resolve': {
    post: {
      tags: ['secrets'],
      summary: 'Resolve a secret to plaintext (audited)',
      requestBody: { content: { 'application/json': { schema: { type: 'object', required: ['name'], properties: { name: { type: 'string' } } } } } },
      responses: { 200: desc('OK'), 403: respRef('Forbidden'), 404: respRef('NotFound') },
    },
  },
  '/api/v1/services': {
    get: { tags: ['services'], summary: 'List visible services', responses: { 200: desc('OK') } },
  },
  '/api/v1/proxy/{service}': {
    post: {
      tags: ['proxy'],
      summary: 'Proxy-mode: call external API (main entry)',
      parameters: [{ in: 'path', name: 'service', required: true, schema: { type: 'string' } }],
      requestBody: { content: { 'application/json': { schema: ref('ProxyRequest') } } },
      responses: {
        200: { description: 'Upstream response' },
        400: respRef('BadRequest'),
        401: respRef('Unauthorized'),
        403: respRef('Forbidden'),
        404: respRef('NotFound'),
        429: respRef('RateLimited'),
        502: { description: 'Upstream error', content: { 'application/json': { schema: ref('Error') } } },
        503: { description: 'Service unavailable (e.g. secret expired)', content: { 'application/json': { schema: ref('Error') } } },
      },
    },
  },
  '/api/v1/api-keys': {
    get: { tags: ['api-keys'], summary: 'List API keys', responses: { 200: jsonOKList('ApiKey') } },
    post: {
      tags: ['api-keys'],
      summary: 'Create API key',
      requestBody: { content: { 'application/json': { schema: { type: 'object', required: ['name'], properties: { name: { type: 'string' }, scopes: { type: 'array', items: { type: 'string' } }, ttl_seconds: { type: 'integer' } } } } } },
      responses: { 200: { description: 'OK, returns key and secret' }, 401: respRef('Unauthorized') },
    },
  },
  '/api/v1/api-keys/{id}': {
    delete: { tags: ['api-keys'], summary: 'Revoke API key', parameters: [{ in: 'path', name: 'id', required: true, schema: { type: 'string' } }], responses: { 200: desc('OK') } },
  },
  '/api/v1/api-keys/master': {
    post: { tags: ['api-keys'], summary: 'Create master key (30d TTL)', responses: { 200: desc('OK') } },
  },
  '/api/v1/api-keys/issue-child': {
    post: { tags: ['api-keys'], summary: 'Issue a child key (master key only)', responses: { 200: desc('OK, 1h TTL') } },
  },
  '/api/v1/admin/secrets': {
    get: { tags: ['admin'], summary: 'List all secrets (admin)', responses: { 200: desc('OK') } },
    post: {
      tags: ['admin'],
      summary: 'Create secret',
      requestBody: { content: { 'application/json': { schema: { type: 'object', required: ['name', 'type'], properties: { name: { type: 'string' }, type: { type: 'string' }, fields: { type: 'object' } } } } } },
      responses: { 200: desc('OK') },
    },
  },
  '/api/v1/admin/services': {
    get: { tags: ['admin'], summary: 'List all services (admin)', responses: { 200: desc('OK') } },
    post: { tags: ['admin'], summary: 'Create service from template', responses: { 200: desc('OK') } },
  },
  '/api/v1/admin/clients': {
    get: { tags: ['admin'], summary: 'List all clients (admin)', responses: { 200: desc('OK') } },
    post: { tags: ['admin'], summary: 'Create client', responses: { 200: desc('OK') } },
  },
  '/api/v1/admin/audit': {
    get: {
      tags: ['admin'],
      summary: 'Query audit log',
      parameters: [
        { in: 'query', name: 'since', schema: { type: 'string' } },
        { in: 'query', name: 'cn', schema: { type: 'string' } },
        { in: 'query', name: 'action', schema: { type: 'string' } },
        { in: 'query', name: 'limit', schema: { type: 'integer', default: 100 } },
      ],
      responses: { 200: desc('OK') },
    },
  },
  '/api/v1/admin/audit/stream': {
    get: { tags: ['admin'], summary: 'SSE stream of audit events', responses: { 200: { description: 'text/event-stream' } } },
  },
  '/api/v1/admin/reload': {
    post: { tags: ['admin'], summary: 'Hot-reload broker.yaml (requires 2FA for admin)', responses: { 200: desc('OK') } },
  },
  '/api/v1/healthcheck/status': {
    get: { tags: ['healthcheck'], summary: 'Last healthcheck state', responses: { 200: desc('OK') } },
  },
  '/api/v1/healthcheck/run': {
    post: { tags: ['healthcheck'], summary: 'Run healthcheck now', responses: { 200: desc('OK') } },
  },
  '/api/v1/healthcheck/stream': {
    get: { tags: ['healthcheck'], summary: 'SSE stream of healthcheck events', responses: { 200: { description: 'text/event-stream' } } },
  },
  '/api/v1/alerts/history': {
    get: { tags: ['admin'], summary: 'Alert history', responses: { 200: desc('OK') } },
  },
  '/api/v1/workload-identity/assume': {
    post: {
      tags: ['admin'],
      summary: 'OIDC to STS assume role (broker-side)',
      requestBody: { content: { 'application/json': { schema: { type: 'object', required: ['provider', 'role'], properties: { provider: { type: 'string', enum: ['aliyun', 'aws', 'gcp'] }, role: { type: 'string' }, oidc_token: { type: 'string' } } } } } },
      responses: { 200: desc('OK') },
    },
  },
  '/api/v2/operations': {
    post: {
      tags: ['operations-v2'],
      summary: 'Create a policy-bound typed operation',
      requestBody: { required: true, content: { 'application/json': { schema: ref('OperationCreate') } } },
      responses: { 202: jsonOK('Operation'), 400: respRef('BadRequest'), 401: respRef('Unauthorized'), 403: respRef('Forbidden') },
    },
  },
  '/api/v2/tools': {
    get: {
      tags: ['tools-v2'],
      summary: 'List registered tools available to the authenticated identity',
      responses: { 200: jsonOK('ToolList'), 401: respRef('Unauthorized'), 503: desc('Tool registry unavailable') },
    },
  },
  '/api/v2/auth/webauthn/begin': {
    post: {
      tags: ['auth-v2'], summary: 'Begin phishing-resistant WebAuthn authentication', security: [],
      requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', additionalProperties: false, required: ['client'], properties: { client: { type: 'string', maxLength: 128 } } } } } },
      responses: { 200: jsonOK('WebAuthnOptions'), 401: respRef('Unauthorized') },
    },
  },
  '/api/v2/auth/webauthn/finish': {
    post: {
      tags: ['auth-v2'], summary: 'Verify WebAuthn assertion and create a short browser session', security: [],
      requestBody: { required: true, content: { 'application/json': { schema: ref('WebAuthnFinish') } } },
      responses: { 200: desc('Authenticated; session is returned only as a secure cookie'), 401: respRef('Unauthorized') },
    },
  },
  '/api/v2/me/webauthn/registration/begin': {
    post: {
      tags: ['auth-v2'], summary: 'Begin security-key registration',
      requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', additionalProperties: false, properties: { label: { type: 'string', maxLength: 80 } } } } } },
      responses: { 200: jsonOK('WebAuthnOptions'), 403: respRef('Forbidden') },
    },
  },
  '/api/v2/me/webauthn/registration/finish': {
    post: {
      tags: ['auth-v2'], summary: 'Verify and store a security-key credential',
      requestBody: { required: true, content: { 'application/json': { schema: ref('WebAuthnFinish') } } },
      responses: { 201: desc('Credential registered'), 403: respRef('Forbidden') },
    },
  },
  '/api/v2/me/webauthn/credentials': {
    get: { tags: ['auth-v2'], summary: 'List public WebAuthn credential metadata', responses: { 200: desc('Credential metadata; no public key bytes') } },
  },
  '/api/v2/operations/{id}': {
    get: {
      tags: ['operations-v2'],
      summary: 'Read a redacted operation result',
      parameters: [{ in: 'path', name: 'id', required: true, schema: { type: 'string', format: 'uuid' } }],
      responses: { 200: jsonOK('Operation'), 401: respRef('Unauthorized'), 403: respRef('Forbidden'), 404: respRef('NotFound') },
    },
  },
  '/api/v2/approvals': {
    post: {
      tags: ['approvals-v2'], summary: 'Create a fully bound approval request',
      requestBody: { required: true, content: { 'application/json': { schema: ref('ApprovalCreate') } } },
      responses: { 201: jsonOK('Approval'), 400: respRef('BadRequest'), 401: respRef('Unauthorized'), 403: respRef('Forbidden'), 409: desc('Approval is not required') },
    },
    get: {
      tags: ['approvals-v2'], summary: 'List approval requests visible to the requester or approver',
      responses: { 200: desc('Approval list'), 401: respRef('Unauthorized') },
    },
  },
  '/api/v2/approvals/{id}/decision': {
    post: {
      tags: ['approvals-v2'], summary: 'Approve or reject in the same-origin WebAuthn browser workbench',
      security: [{ sessionCookie: [] }],
      parameters: [
        { in: 'path', name: 'id', required: true, schema: { type: 'string', format: 'uuid' } },
        { in: 'header', name: 'Origin', required: true, schema: { type: 'string', format: 'uri' }, description: 'Exact configured Broker HTTPS origin' },
      ],
      requestBody: { required: true, content: { 'application/json': { schema: ref('ApprovalDecision') } } },
      responses: { 200: jsonOK('Approval'), 401: respRef('Unauthorized'), 403: respRef('Forbidden'), 404: respRef('NotFound'), 409: desc('Expired, duplicate or completed decision') },
    },
  },
  '/api/v2/browser/otp/claim': {
    post: {
      tags: ['browser-v2'], summary: 'Claim one approved OTP for a bound browser document',
      security: [{ bearerAuth: [] }],
      requestBody: { required: true, content: { 'application/json': { schema: ref('BrowserOtpClaim') } } },
      responses: { 200: jsonOK('BrowserOtpClaimResult'), 401: respRef('Unauthorized'), 403: respRef('Forbidden'), 404: respRef('NotFound') },
    },
  },
  '/api/v2/browser/otp/finish': {
    post: {
      tags: ['browser-v2'], summary: 'Finalize a single-use browser OTP claim',
      security: [{ bearerAuth: [] }],
      requestBody: { required: true, content: { 'application/json': { schema: ref('BrowserOtpFinish') } } },
      responses: { 200: jsonOK('Operation'), 401: respRef('Unauthorized'), 403: respRef('Forbidden'), 409: desc('Claim expired or already consumed') },
    },
  },
  '/api/v2/devices/enroll/begin': {
    post: {
      tags: ['devices-v2'],
      summary: 'Begin proof-of-possession device enrollment',
      requestBody: { required: true, content: { 'application/json': { schema: ref('DeviceEnrollmentBegin') } } },
      responses: { 201: jsonOK('DeviceEnrollmentChallenge'), 401: respRef('Unauthorized'), 403: respRef('Forbidden') },
    },
  },
  '/api/v2/devices/enroll/finish': {
    post: {
      tags: ['devices-v2'],
      summary: 'Finish device enrollment with a supported hardware-backed signature',
      security: [],
      requestBody: { required: true, content: { 'application/json': { schema: ref('DeviceEnrollmentFinish') } } },
      responses: { 201: jsonOK('Device'), 400: respRef('BadRequest'), 401: respRef('Unauthorized'), 403: respRef('Forbidden') },
    },
  },
  '/api/v2/devices': {
    get: { tags: ['devices-v2'], summary: 'List visible devices without public keys or secrets', responses: { 200: desc('Device list'), 401: respRef('Unauthorized') } },
  },
  '/api/v2/devices/{device_id}': {
    patch: {
      tags: ['devices-v2'], summary: 'Suspend or permanently revoke a device',
      parameters: [{ in: 'path', name: 'device_id', required: true, schema: { type: 'string', format: 'uuid' } }],
      requestBody: { required: true, content: { 'application/json': { schema: {
        type: 'object', additionalProperties: false, required: ['state', 'approval_request_id'],
        properties: {
          state: { type: 'string', enum: ['active', 'suspended', 'revoked'] },
          approval_request_id: { type: 'string', format: 'uuid', description: 'Two-person approval bound to this device and requested state' },
        },
      } } } },
      responses: { 200: jsonOK('Device'), 401: respRef('Unauthorized'), 403: respRef('Forbidden'), 404: respRef('NotFound'), 409: desc('Invalid state transition') },
    },
  },
  '/api/v2/devices/{device_id}/otp-tasks': {
    get: {
      tags: ['devices-v2'], summary: 'List pending OTP task metadata for a signed device request', security: [],
      parameters: [
        { in: 'path', name: 'device_id', required: true, schema: { type: 'string', format: 'uuid' } },
        { in: 'header', name: 'X-Broker-Device-Timestamp', required: true, schema: { type: 'integer' } },
        { in: 'header', name: 'X-Broker-Device-Nonce', required: true, schema: { type: 'string' } },
        { in: 'header', name: 'X-Broker-Device-Signature', required: true, schema: { type: 'string' } },
      ],
      responses: { 200: { description: 'Pending task metadata; never contains an OTP', content: { 'application/json': { schema: { type: 'object', required: ['tasks'], properties: { tasks: { type: 'array', items: ref('OtpTask') } } } } } }, 401: respRef('Unauthorized'), 403: respRef('Forbidden') },
    },
  },
  '/api/v2/devices/{device_id}/suspend': {
    post: {
      tags: ['devices-v2'], summary: 'Let a device immediately suspend itself with a signed empty request', security: [],
      parameters: [
        { in: 'path', name: 'device_id', required: true, schema: { type: 'string', format: 'uuid' } },
        { in: 'header', name: 'X-Broker-Device-Timestamp', required: true, schema: { type: 'integer' } },
        { in: 'header', name: 'X-Broker-Device-Nonce', required: true, schema: { type: 'string' } },
        { in: 'header', name: 'X-Broker-Device-Signature', required: true, schema: { type: 'string' } },
      ],
      requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', additionalProperties: false } } } },
      responses: { 200: jsonOK('Device'), 400: respRef('BadRequest'), 401: respRef('Unauthorized'), 503: desc('Audit or persistence unavailable') },
    },
  },
  '/api/v2/devices/{device_id}/otp-tasks/{task_id}/submit': {
    post: {
      tags: ['devices-v2'], summary: 'Submit an OTP to a pre-existing bound task', security: [],
      parameters: [
        { in: 'path', name: 'device_id', required: true, schema: { type: 'string', format: 'uuid' } },
        { in: 'path', name: 'task_id', required: true, schema: { type: 'string', format: 'uuid' } },
        { in: 'header', name: 'X-Broker-Device-Timestamp', required: true, schema: { type: 'integer' } },
        { in: 'header', name: 'X-Broker-Device-Nonce', required: true, schema: { type: 'string' } },
        { in: 'header', name: 'X-Broker-Device-Signature', required: true, schema: { type: 'string' } },
      ],
      requestBody: { required: true, content: { 'application/json': { schema: ref('OtpSubmission') } } },
      responses: { 202: desc('Accepted without echoing the OTP'), 400: respRef('BadRequest'), 401: respRef('Unauthorized'), 403: respRef('Forbidden') },
    },
  },
  '/api/v2/devices/{device_id}/browser-leases/claim': {
    post: {
      tags: ['browser-workers-v2'], summary: 'Claim the oldest typed browser operation allowed by an enrolled worker capability', security: [],
      parameters: [
        { in: 'path', name: 'device_id', required: true, schema: { type: 'string', format: 'uuid' } },
        { in: 'header', name: 'X-Broker-Device-Timestamp', required: true, schema: { type: 'integer' } },
        { in: 'header', name: 'X-Broker-Device-Nonce', required: true, schema: { type: 'string' } },
        { in: 'header', name: 'X-Broker-Device-Signature', required: true, schema: { type: 'string' } },
      ],
      requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', additionalProperties: false } } } },
      responses: { 200: jsonOK('BrowserOperationLease'), 401: respRef('Unauthorized'), 404: respRef('NotFound'), 409: desc('Lease or operation state conflict') },
    },
  },
  '/api/v2/devices/{device_id}/browser-leases/{lease_id}/otp': {
    post: {
      tags: ['browser-workers-v2'], summary: 'Consume the single OTP bound to an active browser operation lease', security: [],
      parameters: [
        { in: 'path', name: 'device_id', required: true, schema: { type: 'string', format: 'uuid' } },
        { in: 'path', name: 'lease_id', required: true, schema: { type: 'string', format: 'uuid' } },
        { in: 'header', name: 'X-Broker-Device-Timestamp', required: true, schema: { type: 'integer' } },
        { in: 'header', name: 'X-Broker-Device-Nonce', required: true, schema: { type: 'string' } },
        { in: 'header', name: 'X-Broker-Device-Signature', required: true, schema: { type: 'string' } },
      ],
      requestBody: { required: true, content: { 'application/json': { schema: ref('BrowserLeaseReceipt') } } },
      responses: { 200: jsonOK('BrowserLeaseOtp'), 401: respRef('Unauthorized'), 409: desc('Lease invalid, expired, or OTP unavailable') },
    },
  },
  '/api/v2/devices/{device_id}/browser-leases/{lease_id}/complete': {
    post: {
      tags: ['browser-workers-v2'], summary: 'Complete or fail an active browser operation lease with a redacted result', security: [],
      parameters: [
        { in: 'path', name: 'device_id', required: true, schema: { type: 'string', format: 'uuid' } },
        { in: 'path', name: 'lease_id', required: true, schema: { type: 'string', format: 'uuid' } },
        { in: 'header', name: 'X-Broker-Device-Timestamp', required: true, schema: { type: 'integer' } },
        { in: 'header', name: 'X-Broker-Device-Nonce', required: true, schema: { type: 'string' } },
        { in: 'header', name: 'X-Broker-Device-Signature', required: true, schema: { type: 'string' } },
      ],
      requestBody: { required: true, content: { 'application/json': { schema: ref('BrowserLeaseCompletion') } } },
      responses: { 200: jsonOK('Operation'), 400: respRef('BadRequest'), 401: respRef('Unauthorized'), 409: desc('Lease invalid, expired, or already completed') },
    },
  },
};

const s = {
  Error: {
    type: 'object',
    required: ['error'],
    properties: {
      error: { type: 'string' },
      detail: { type: 'string' },
      request_id: { type: 'string' },
      retry_after_ms: { type: 'integer' },
      docs: { type: 'string' },
    },
  },
  ProxyRequest: {
    type: 'object',
    required: ['method', 'path'],
    properties: {
      method: { type: 'string', enum: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'] },
      path: { type: 'string', pattern: '^/', maxLength: 2048 },
      query: { type: 'object', additionalProperties: { type: 'string' } },
      headers: { type: 'object', additionalProperties: { type: 'string' } },
      body: {},
      timeout_ms: { type: 'integer', minimum: 1000, maximum: 60000, default: 30000 },
      stream: { type: 'boolean', default: false },
    },
  },
  LoginRequest: {
    type: 'object',
    required: ['password'],
    properties: {
      client: { type: 'string' },
      password: { type: 'string', format: 'password' },
    },
  },
  LoginResponse: {
    type: 'object',
    properties: {
      expires_at: { type: 'string', format: 'date-time' },
      cn: { type: 'string' },
      role: { type: 'string', enum: ['developer', 'admin', 'ci'] },
      mfa_required: { type: 'boolean' },
      mfa_token: { type: 'string' },
      factors_verified: { type: 'array', items: { type: 'string' } },
    },
  },
  Me: {
    type: 'object',
    properties: {
      name: { type: 'string' },
      cn: { type: 'string' },
      role: { type: 'string' },
      allow_password_login: { type: 'boolean' },
      has_password: { type: 'boolean' },
      password_set_at: { type: 'string', format: 'date-time' },
      totp_enabled: { type: 'boolean' },
      preferred_2fa: { type: 'string' },
      cert_fingerprint_sha256: { type: 'string' },
      cert_expires_at: { type: 'string', format: 'date-time' },
      risk_score: { type: 'number' },
      rate_limit: { type: 'string' },
    },
  },
  ApiKey: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      name: { type: 'string' },
      client: { type: 'string' },
      scopes: { type: 'array', items: { type: 'string' } },
      rate_limit: { type: 'string' },
      rate_limit_per_minute: { type: 'integer' },
      rate_limit_per_hour: { type: 'integer' },
      rate_limit_per_day: { type: 'integer' },
      ip_whitelist: { type: 'array', items: { type: 'string' } },
      allowed_secrets: { type: 'array', items: { type: 'string' } },
      allowed_services: { type: 'array', items: { type: 'string' } },
      allowed_operations: { type: 'array', items: { type: 'string' } },
      allowed_accounts: { type: 'array', items: { type: 'string' } },
      allowed_resources: { type: 'array', items: { type: 'string' } },
      allowed_environments: { type: 'array', items: { type: 'string' } },
      created_at: { type: 'string', format: 'date-time' },
      expires_at: { type: 'string', format: 'date-time' },
      revoked_at: { type: 'string', format: 'date-time' },
      is_master: { type: 'boolean' },
      fingerprint_prefix: { type: 'string' },
    },
  },
  Secret: {
    type: 'object',
    properties: {
      name: { type: 'string' },
      type: { type: 'string' },
      description: { type: 'string' },
      last_used_at: { type: 'string', format: 'date-time' },
      last_rotated_at: { type: 'string', format: 'date-time' },
      has_value: { type: 'boolean' },
    },
  },
  Service: {
    type: 'object',
    properties: {
      name: { type: 'string' },
      type: { type: 'string' },
      auth_type: { type: 'string' },
      upstream: { type: 'string' },
      category: { type: 'string' },
      allow_methods: { type: 'array', items: { type: 'string' } },
      allow_paths: { type: 'array', items: { type: 'string' } },
      healthcheck: { type: 'object' },
    },
  },
  Health: {
    type: 'object',
    properties: {
      status: { type: 'string', enum: ['ok', 'degraded', 'down'] },
      version: { type: 'string' },
      sops_loaded: { type: 'boolean' },
      services_count: { type: 'number' },
      uptime_seconds: { type: 'number' },
    },
  },
  ToolList: {
    type: 'object', additionalProperties: false, required: ['registry_version', 'tools'],
    properties: {
      registry_version: { type: 'integer', const: 1 },
      tools: { type: 'array', items: ref('ToolRegistration') },
    },
  },
  ToolRegistration: {
    type: 'object', additionalProperties: false,
    required: ['name', 'version', 'description', 'provider', 'operation_id', 'input_schema', 'output_schema', 'required_role', 'risk_level', 'environments', 'target', 'timeout_ms', 'rate_limit', 'approval_policy', 'audit_policy', 'agent_execution'],
    properties: {
      name: { type: 'string' }, version: { type: 'string' }, description: { type: 'string' },
      provider: { type: 'string' }, operation_id: { type: 'string' },
      input_schema: { type: 'object' }, output_schema: { type: 'object' },
      required_role: { type: 'string', enum: ['viewer', 'developer', 'operator', 'admin'] },
      risk_level: { type: 'string', enum: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] },
      environments: { type: 'array', items: { type: 'string', enum: ['development', 'staging', 'production'] } },
      target: { type: 'object' }, timeout_ms: { type: 'integer' }, rate_limit: { type: 'object' },
      approval_policy: { type: 'object' }, audit_policy: { type: 'object' }, agent_execution: { type: 'boolean' },
    },
  },
  OperationCreate: {
    type: 'object', additionalProperties: false,
    required: ['provider', 'operation_id', 'account_ref', 'environment', 'typed_parameters'],
    properties: {
      provider: { type: 'string', pattern: '^[a-z][a-z0-9_-]{1,63}$' },
      operation_id: { type: 'string', pattern: '^[a-z][a-z0-9_.-]{1,127}$' },
      account_ref: { type: 'string', minLength: 1, maxLength: 128 },
      environment: { type: 'string', enum: ['development', 'staging', 'production'] },
      typed_parameters: { type: 'object' },
      approval_request_id: { type: 'string', format: 'uuid', description: 'Single-use approval bound to this exact request' },
      otp: ref('OtpRequirement'),
    },
  },
  ApprovalCreate: {
    type: 'object', additionalProperties: false,
    required: ['provider', 'operation_id', 'account_ref', 'environment', 'typed_parameters'],
    properties: {
      provider: { type: 'string', pattern: '^[a-z][a-z0-9_-]{1,63}$' },
      operation_id: { type: 'string', pattern: '^[a-z][a-z0-9_.-]{1,127}$' },
      account_ref: { type: 'string', minLength: 1, maxLength: 128 },
      environment: { type: 'string', enum: ['development', 'staging', 'production'] },
      typed_parameters: { type: 'object' },
    },
  },
  ApprovalDecision: {
    type: 'object', additionalProperties: false, required: ['decision'],
    properties: { decision: { type: 'string', enum: ['approve', 'reject'] } },
  },
  Approval: {
    type: 'object', additionalProperties: false,
    required: ['id', 'requester', 'provider', 'operation_id', 'account_ref', 'environment', 'resource_ref', 'required_approvals', 'approvals', 'status', 'created_at', 'expires_at'],
    properties: {
      id: { type: 'string', format: 'uuid' }, requester: { type: 'string' }, provider: { type: 'string' },
      operation_id: { type: 'string' }, account_ref: { type: 'string' }, environment: { type: 'string' },
      resource_ref: { type: 'string' }, required_approvals: { type: 'integer', minimum: 1, maximum: 10 },
      approvals: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['approved_by', 'approved_at'], properties: { approved_by: { type: 'string' }, approved_at: { type: 'string', format: 'date-time' } } } },
      status: { type: 'string', enum: ['pending', 'approved', 'rejected', 'expired', 'consumed'] },
      created_at: { type: 'string', format: 'date-time' }, expires_at: { type: 'string', format: 'date-time' },
    },
  },
  OtpRequirement: {
    type: 'object', additionalProperties: false,
    required: ['device_id', 'sim_binding', 'challenge', 'recipient_hint'],
    properties: {
      device_id: { type: 'string', format: 'uuid' }, sim_binding: { type: 'string', maxLength: 128 },
      challenge: { type: 'string', maxLength: 256 }, recipient_hint: { type: 'string', maxLength: 64 },
      template_group: { type: 'string', maxLength: 64 }, ttl_seconds: { type: 'integer', minimum: 15, maximum: 120 },
    },
  },
  Operation: {
    type: 'object', required: ['id', 'provider', 'operation_id', 'status'],
    properties: {
      id: { type: 'string', format: 'uuid' }, provider: { type: 'string' }, operation_id: { type: 'string' },
      account_ref: { type: 'string' }, environment: { type: 'string' },
      execution_mode: { type: 'string', enum: ['adapter', 'browser'] },
      status: { type: 'string', enum: ['waiting', 'received', 'consuming', 'completed', 'failed', 'expired', 'revoked'] },
      result: { type: 'object' }, error: { type: 'object' }, created_at: { type: 'string', format: 'date-time' },
      updated_at: { type: 'string', format: 'date-time' }, expires_at: { type: 'string', format: 'date-time' },
      otp_task_id: { oneOf: [{ type: 'string', format: 'uuid' }, { type: 'null' }] },
    },
  },
  DeviceEnrollmentBegin: {
    type: 'object', additionalProperties: false, required: ['label', 'platform', 'approval_request_id'],
    properties: {
      label: { type: 'string', maxLength: 80 },
      platform: { type: 'string', enum: ['android', 'windows', 'linux', 'ios', 'browser-worker'] },
      capabilities: {
        type: 'array', items: { type: 'string' },
        description: 'Browser worker grants use browser.execute:<provider>:<operation>:<account>:<environment>.',
      },
      approval_request_id: { type: 'string', format: 'uuid', description: 'Two-person approval bound to the complete enrollment request' },
    },
  },
  DeviceEnrollmentChallenge: {
    type: 'object', required: ['enrollment_id', 'challenge', 'expires_at'],
    properties: { enrollment_id: { type: 'string', format: 'uuid' }, challenge: { type: 'string' }, expires_at: { type: 'string', format: 'date-time' } },
  },
  DeviceEnrollmentFinish: {
    type: 'object', additionalProperties: false, required: ['enrollment_id', 'signature_algorithm', 'public_key_pem', 'signature'],
    properties: {
      enrollment_id: { type: 'string', format: 'uuid' },
      signature_algorithm: { type: 'string', enum: ['ed25519', 'p256-sha256'] },
      public_key_pem: { type: 'string', description: 'PEM encoded Ed25519 or NIST P-256 public key' },
      signature: { type: 'string', description: 'Base64url signature over the enrollment challenge' },
    },
  },
  Device: {
    type: 'object', required: ['id', 'label', 'platform', 'signature_algorithm', 'state'],
    properties: { id: { type: 'string', format: 'uuid' }, label: { type: 'string' }, platform: { type: 'string' }, signature_algorithm: { type: 'string', enum: ['ed25519', 'p256-sha256'] }, state: { type: 'string', enum: ['active', 'suspended', 'revoked'] }, capabilities: { type: 'array', items: { type: 'string' } }, created_at: { type: 'string', format: 'date-time' } },
  },
  OtpTask: {
    type: 'object', additionalProperties: false,
    required: ['id', 'operation_id', 'device_id', 'sim_binding', 'provider', 'template_group', 'sender_allowlist', 'challenge', 'status', 'created_at', 'expires_at'],
    properties: {
      id: { type: 'string', format: 'uuid' }, operation_id: { type: 'string', format: 'uuid' }, device_id: { type: 'string', format: 'uuid' },
      sim_binding: { type: 'string' }, provider: { type: 'string' }, template_group: { type: 'string' },
      sender_allowlist: { type: 'array', minItems: 1, maxItems: 16, items: { type: 'string', maxLength: 64 } }, challenge: { type: 'string' },
      status: { type: 'string', enum: ['waiting', 'received', 'consuming', 'completed', 'failed', 'expired', 'revoked'] },
      created_at: { type: 'string', format: 'date-time' }, expires_at: { type: 'string', format: 'date-time' },
    },
  },
  OtpSubmission: {
    type: 'object', additionalProperties: false, required: ['code', 'sim_binding', 'challenge'],
    properties: { code: { type: 'string', pattern: '^[0-9]{4,10}$' }, sim_binding: { type: 'string' }, challenge: { type: 'string' } },
  },
  BrowserLeaseReceipt: {
    type: 'object', additionalProperties: false, required: ['receipt'],
    properties: { receipt: { type: 'string', minLength: 32, maxLength: 128 } },
  },
  BrowserOperationLease: {
    type: 'object', additionalProperties: false, required: ['id', 'receipt', 'expires_at', 'operation'],
    properties: {
      id: { type: 'string', format: 'uuid' }, receipt: { type: 'string', minLength: 32, maxLength: 128 },
      expires_at: { type: 'string', format: 'date-time' },
      operation: {
        type: 'object', additionalProperties: false,
        required: ['id', 'provider', 'operation_id', 'account_ref', 'environment', 'typed_parameters', 'otp_available'],
        properties: {
          id: { type: 'string', format: 'uuid' }, provider: { type: 'string' }, operation_id: { type: 'string' },
          account_ref: { type: 'string' }, environment: { type: 'string' }, typed_parameters: { type: 'object' },
          otp_available: { type: 'boolean' },
        },
      },
    },
  },
  BrowserLeaseOtp: {
    type: 'object', additionalProperties: false, required: ['code', 'expires_at'],
    properties: { code: { type: 'string', pattern: '^[0-9]{4,10}$' }, expires_at: { type: 'string', format: 'date-time' } },
  },
  BrowserLeaseCompletion: {
    type: 'object', additionalProperties: false, required: ['receipt', 'status'],
    properties: {
      receipt: { type: 'string', minLength: 32, maxLength: 128 },
      status: { type: 'string', enum: ['completed', 'failed'] }, result: { type: 'object' },
      error_code: { type: 'string', pattern: '^[a-z0-9][a-z0-9._:-]{0,127}$' },
    },
  },
  BrowserOtpClaim: {
    type: 'object', additionalProperties: false,
    required: ['provider', 'account_ref', 'origin', 'tab_id', 'frame_id', 'document_id'],
    properties: {
      provider: { type: 'string', enum: ['aliyun', 'tencent'] },
      account_ref: { type: 'string', pattern: '^[a-z0-9][a-z0-9._:-]{0,127}$' },
      origin: { type: 'string', enum: ['https://account.aliyun.com', 'https://cloud.tencent.com'] },
      tab_id: { type: 'integer', minimum: 0 }, frame_id: { type: 'integer', const: 0 },
      document_id: { type: 'string', minLength: 1, maxLength: 256 },
    },
  },
  BrowserOtpClaimResult: {
    type: 'object', additionalProperties: false,
    required: ['type', 'provider', 'account_ref', 'origin', 'tab_id', 'frame_id', 'document_id', 'expires_at_ms', 'code', 'receipt'],
    properties: {
      type: { type: 'string', const: 'approved-otp' }, provider: { type: 'string' }, origin: { type: 'string' },
      account_ref: { type: 'string' },
      tab_id: { type: 'integer' }, frame_id: { type: 'integer' }, document_id: { type: 'string' },
      expires_at_ms: { type: 'integer' }, code: { type: 'string', pattern: '^[0-9]{4,10}$' }, receipt: { type: 'string' },
    },
  },
  BrowserOtpFinish: {
    type: 'object', additionalProperties: false, required: ['receipt', 'completed'],
    properties: { receipt: { type: 'string', minLength: 1, maxLength: 128 }, completed: { type: 'boolean' } },
  },
  WebAuthnOptions: {
    type: 'object', additionalProperties: false, required: ['flow_id', 'options'],
    properties: { flow_id: { type: 'string', format: 'uuid' }, options: { type: 'object', additionalProperties: true } },
  },
  WebAuthnFinish: {
    type: 'object', additionalProperties: false, required: ['flow_id', 'response'],
    properties: { flow_id: { type: 'string', format: 'uuid' }, response: { type: 'object', additionalProperties: true } },
  },
};

const r = {
  BadRequest: { description: 'Bad request', content: { 'application/json': { schema: ref('Error') } } },
  Unauthorized: { description: 'Unauthenticated', content: { 'application/json': { schema: ref('Error') } } },
  Forbidden: { description: 'Forbidden', content: { 'application/json': { schema: ref('Error') } } },
  NotFound: { description: 'Not found', content: { 'application/json': { schema: ref('Error') } } },
  RateLimited: { description: 'Rate limited', content: { 'application/json': { schema: ref('Error') } } },
  InternalError: { description: 'Internal error', content: { 'application/json': { schema: ref('Error') } } },
};

export const OPENAPI_SPEC = {
  openapi: '3.1.0',
  info: {
    title: 'Secret Broker API',
    version: BROKER_VERSION,
    description: 'mTLS Secret Broker for AI clients. AI never sees plaintext keys.',
  },
  servers: [
    { url: 'https://broker.example.com', description: 'Aliyun production' },
    { url: 'https://broker-bk.example.com', description: 'Tencent production (failover)' },
    { url: 'https://localhost:8443', description: 'Local development with a trusted test CA' },
  ],
  security: [{ mtls: [] }, { bearerAuth: [] }, { sessionCookie: [] }],
  tags: [
    { name: 'health', description: 'Health / ready / metrics' },
    { name: 'auth', description: 'Authentication' },
    { name: 'auth-v2', description: 'WebAuthn authentication and security-key lifecycle' },
    { name: 'me', description: 'Self-service profile' },
    { name: 'secrets', description: 'Secret listing and resolve' },
    { name: 'services', description: 'Service listing' },
    { name: 'proxy', description: 'Proxy external API' },
    { name: 'api-keys', description: 'API Key management' },
    { name: 'admin', description: 'Admin operations' },
    { name: 'healthcheck', description: 'Credential self-check' },
    { name: 'operations-v2', description: 'Policy-bound typed operations' },
    { name: 'tools-v2', description: 'Versioned, risk-classified tool registry' },
    { name: 'approvals-v2', description: 'Bound, WebAuthn-stepped-up approvals with separation of duties' },
    { name: 'devices-v2', description: 'Device proof-of-possession and bound OTP tasks' },
    { name: 'browser-workers-v2', description: 'Signed short-lived leases for isolated typed browser operations' },
  ],
  paths: p,
  components: {
    securitySchemes: {
      mtls: { type: 'mutualTLS', description: 'mTLS client certificate' },
      bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'API Key (mb_live_xxx)' },
      sessionCookie: { type: 'apiKey', in: 'cookie', name: 'broker_session' },
    },
    schemas: s,
    responses: r,
  },
};

export default OPENAPI_SPEC;
