# Start Secret Broker V4.1.0 detached for local dev
$ErrorActionPreference = 'Continue'
$env:PKI_DIR = 'E:\broker\pki'
$env:AUDIT_DIR = 'E:\broker\audit'
$env:SECRETS_DETAIL_PATH = 'E:\broker\secrets\secrets-detail.json'
$env:BROKER_CONFIG_PATH = 'E:\broker\secrets\broker.yaml'
$env:CONFIG_PATH = 'E:\broker\secrets\broker.yaml'
$env:CONFIG_BASE = 'E:\broker\secrets'
$env:CLIENTS_JSON = 'E:\broker\secrets\clients.json'
$env:CA_CERT_PATH = 'E:\broker\pki\ca\ca.crt'
$env:CA_KEY_PATH = 'E:\broker\pki\ca\ca.key'
$env:TLS_CA = 'E:\broker\pki\ca\ca.crt'
$env:TLS_CERT = 'E:\broker\pki\server\server.crt'
$env:TLS_KEY = 'E:\broker\pki\server\server.key'
$env:TLS_CRL = 'C:\nonexistent.crl'
$env:BROKER_PORT = '8443'
$env:BROKER_BIND = '127.0.0.1'
$env:NODE_ENV = 'development'
$env:SOPS_SKIP = '1'
Set-Location 'E:\broker\broker'
node server.js 2>&1
